import React from 'react';
import { ArrowRight, Check, ShieldCheck } from 'lucide-react';
import { AvailabilityPicker, BookingSummary, Button, Card, DurationSelector, Label, MentorIdentity, PaymentStatus } from '@devmentor/ui';
import { EmptyState } from '@devmentor/ui/backend';
import { PublicPage, Screen } from './Frame';
import { navigate } from './navigation';
import { dateLabel, groupSlots, money, timeLabel, TIME_ZONES, type Slot } from './flow';

export interface BookingScreensProps {
  mentorName?:string; slots:Slot[]; selected:Slot|null; duration:25|50; prices:{25:number;50:number}; timeZone:string; signedIn:boolean;
  onSelect:(id:string)=>void; onDuration:(duration:25|50)=>void; onTimeZone:(zone:string)=>void;
  onOutcome:(outcome:'confirmed'|'failed'|'slot-taken'|'expired')=>void;
  conflict:'slot-taken'|'expired';
}
function BookingSteps({current}:{current:number}) {
  return <ol className="proto-booking-steps" aria-label="Booking progress">{['Time & length','Your account','Confirm booking'].map((name,index)=><li key={name} aria-current={current===index?'step':undefined}><span aria-hidden="true">{index<current?<Check size={14}/>:index+1}</span>{name}</li>)}</ol>;
}
function BookingDetails({p,actions}:{p:BookingScreensProps;actions?:React.ReactNode}) {
  return p.selected ? <BookingSummary mentorName={p.mentorName??'Alex Laurent'} startsAt={p.selected.start} dateLabel={dateLabel(p.selected.start,p.timeZone)} timeLabel={timeLabel(p.selected.start,p.timeZone)} timeZone={p.timeZone} duration={p.duration} total={money(p.prices[p.duration])} actions={actions} /> : <EmptyState title="Choose your session time" description="Select a time and length before continuing." action={<Button onClick={()=>navigate('s3')}>Choose a time</Button>} />;
}
export function BookingScreens(p:BookingScreensProps) {
  const days=groupSlots(p.slots,p.timeZone);
  return <>
    <Screen id="s2" title="No available times" description="The mentor's profile stays visible when no times are available." refs={['#17','#21']}><PublicPage back="s1"><div className="proto-narrow proto-stack"><MentorIdentity name={p.mentorName??'Alex Laurent'} headline="Text mentoring" initials={(p.mentorName??'Alex Laurent').split(' ').map(word=>word[0]).slice(0,2).join('')} /><EmptyState title="No times available right now" description="This mentor has no published times starting at least two hours from now. Check this page again later." action={<Button intent="neutral" appearance="stroke" onClick={()=>navigate('s1')}>Back to mentor profile</Button>} /></div></PublicPage></Screen>
    <Screen id="s3" title="Choose a session" description="Choose a time, timezone and session length. The summary updates with your selection and price." refs={['#18','#21']} note="The demo clock is fixed at 10 September 2026, 08:00 UTC. The time less than two hours away is disabled. Changing timezone updates the labels while keeping the same selected time."><PublicPage back="s1"><BookingSteps current={0}/><div className="proto-page-heading"><p className="proto-eyebrow">Session with {p.mentorName??'Alex Laurent'}</p><h1>Choose your session time</h1><p>Choose a 25-minute session, or spend 50 minutes working through the problem together.</p></div><div className="proto-booking-grid"><Card className="dm-product-panel"><div className="proto-stack"><MentorIdentity name={p.mentorName??'Alex Laurent'} headline="Text mentoring" initials={(p.mentorName??'Alex Laurent').split(' ').map(word=>word[0]).slice(0,2).join('')} /><div className="dm-field"><Label htmlFor="booking-timezone">Your timezone</Label><select id="booking-timezone" className="dm-input" value={p.timeZone} onChange={e=>p.onTimeZone(e.target.value)}>{TIME_ZONES.map(zone=><option key={zone}>{zone}</option>)}</select></div><AvailabilityPicker days={days} timeZone={p.timeZone} selectedSlotId={p.selected?.id??null} onSlotChange={p.onSelect}/><DurationSelector options={[{minutes:25,price:money(p.prices[25])},{minutes:50,price:money(p.prices[50])}]} selected={p.duration} onChange={p.onDuration}/></div></Card><div className="proto-stack"><BookingDetails p={p}/><Button className="proto-full-button" disabled={!p.selected} onClick={()=>navigate(p.signedIn?'s4':'s12')}>Continue<ArrowRight aria-hidden="true" /></Button><p className="dm-product-caption">Your booking is confirmed only after payment is verified.</p></div></div></PublicPage></Screen>
    <Screen id="s4" title="Booking summary" description="Review the selected time, duration and total." refs={['#22','#34']}><PublicPage back="s3"><BookingSteps current={2}/><div className="proto-narrow proto-stack"><div className="proto-page-heading"><p className="proto-eyebrow">Booking summary</p><h1>Check your booking</h1><p>After your text session, you receive a written answer and a private session note.</p></div><BookingDetails p={p} actions={<Button onClick={()=>navigate('s14')}>Continue to checkout<ArrowRight aria-hidden="true" /></Button>}/><p className="proto-reassurance"><ShieldCheck aria-hidden="true" />We confirm your booking after secure payment verification.</p></div></PublicPage></Screen>
    <Screen id="s5" title="Payment needs attention" description="Check the payment again without losing your selected session." refs={['#22']} note="This screen does not confirm whether you were charged. In production, check the payment provider's result before retrying."><PublicPage back="s4"><div className="proto-narrow proto-stack"><h1 className="proto-title">Check your payment</h1><PaymentStatus state="failed" reference="DEMO-SESSION-1042" actions={<><Button onClick={()=>navigate('s14')}>Check demo payment again</Button><Button intent="neutral" appearance="stroke" onClick={()=>navigate('s3')}>Choose another time</Button></>}/><BookingDetails p={p}/></div></PublicPage></Screen>
    <Screen id="s13" title="Reservation changed" description="Choose another time if the slot is taken or the reservation expires." refs={['#21','#22']}><PublicPage back="s3"><div className="proto-narrow proto-stack"><h1 className="proto-title">Choose a new time</h1><PaymentStatus state={p.conflict} actions={<Button onClick={()=>navigate('s3')}>See available times<ArrowRight aria-hidden="true" /></Button>}/></div></PublicPage></Screen>
    <Screen id="s14" title="Demo checkout" description="Try a pending, confirmed or failed payment without spending money." refs={['#22','#34']} note="The result buttons below are demo controls. They simulate a verified payment result without opening Stripe or collecting payment details."><PublicPage back="s4"><div className="proto-narrow proto-stack"><div className="proto-page-heading"><p className="proto-eyebrow">Local payment simulation</p><h1>Demo checkout</h1><p>This demo does not collect payment details or charge money.</p></div><PaymentStatus state="pending"/><BookingDetails p={p}/><Card className="dm-product-panel proto-simulation"><h2 className="dm-product-title">Choose a demo result</h2><div className="dm-product-actions"><Button onClick={()=>p.onOutcome('confirmed')}>Confirm demo payment</Button><Button intent="neutral" appearance="stroke" onClick={()=>p.onOutcome('failed')}>Payment failed</Button><Button intent="neutral" appearance="ghost" onClick={()=>p.onOutcome('slot-taken')}>Slot taken</Button><Button intent="neutral" appearance="ghost" onClick={()=>p.onOutcome('expired')}>Hold expired</Button></div></Card></div></PublicPage></Screen>
  </>;
}
