import { defineConfig } from 'vitest/config';

// No React plugin is configured on purpose. Vitest's built-in esbuild transform already
// compiles `.tsx` with the automatic JSX runtime (`"jsx": "react-jsx"` in tsconfig.base.json),
// which is everything a component test needs. `@vitejs/plugin-react` only adds Fast Refresh and
// Babel-only transforms (e.g. the React Compiler), neither of which runs under `vitest run`, so
// adding it here would be configuration that changes nothing.
export default defineConfig({
  test: {
    // Node is the default so the existing node-only tests keep running unchanged. React
    // component tests opt in per file with a `// @vitest-environment jsdom` pragma on line 1.
    environment: 'node',
    include: [
      'packages/**/*.test.ts',
      'packages/**/*.test.tsx',
      // The `npm run setup` installer lives outside packages/; without this its tests
      // would never be collected and its coverage gate would pass vacuously.
      'scripts/**/*.test.mjs',
    ],
    exclude: [
      'tests/integration/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/dist/**',
    ],
    coverage: {
      provider: 'v8',
      include: [
        // Route files with a decision in them. `/api/users` guards `GET` at the route as
        // well as in the service; the three auth routes decide the whole OAuth ordering,
        // the `?login` rule and the sign-out contract, so all of it is production behavior
        // and is covered like any other.
        'packages/app/src/app/api/auth/github/route.ts',
        'packages/app/src/app/api/auth/github/callback/route.ts',
        'packages/app/src/app/api/auth/logout/route.ts',
        'packages/app/src/app/api/users/route.ts',
        'packages/app/src/lib/session.ts',
        'packages/app/src/lib/sign-in-redirect.ts',
        'packages/core/src/config/env.ts',
        'packages/core/src/container/container.ts',
        'packages/core/src/http/apiHandler.ts',
        'packages/core/src/http/auth.ts',
        'packages/core/src/http/cookies.ts',
        'packages/core/src/http/errors.ts',
        'packages/core/src/http/makeCrudRoute.ts',
        'packages/core/src/http/outbound.ts',
        'packages/core/src/http/return-to.ts',
        'packages/core/src/services/auth/adapters/github-identity.ts',
        'packages/core/src/services/auth/adapters/mock-github-identity.ts',
        'packages/core/src/services/auth/github-identity.port.ts',
        'packages/core/src/services/auth/oauth-state.ts',
        'packages/core/src/services/auth/operator-authority.ts',
        'packages/core/src/services/auth/session-secret.ts',
        'packages/core/src/services/auth/session.service.ts',
        'packages/core/src/services/auth/token.service.ts',
        'packages/core/src/services/auth/user.service.ts',
        'packages/core/src/time/clock.ts',
        'packages/db/src/config.ts',
        'packages/db/src/entities/auth/roles.ts',
        'packages/db/src/entities/auth/user.entity.ts',
        'packages/db/src/seeders/database.seeder.ts',
        'packages/ui/src/backend/feedback/EmptyState.tsx',
        'packages/ui/src/backend/feedback/ErrorMessage.tsx',
        'packages/ui/src/backend/feedback/LoadingMessage.tsx',
        'packages/ui/src/backend/forms/CrudForm.tsx',
        'packages/ui/src/backend/forms/FormField.tsx',
        'packages/ui/src/backend/shell/AppShell.tsx',
        'packages/ui/src/backend/shell/AuthLayout.tsx',
        'packages/ui/src/backend/tables/DataTable.tsx',
        'packages/ui/src/components/auth/AccessStatus.tsx',
        'packages/ui/src/components/auth/AccountForm.tsx',
        'packages/ui/src/components/auth/AuthFeedback.tsx',
        'packages/ui/src/components/availability/AvailabilityPicker.tsx',
        'packages/ui/src/components/bookings/BookingSummary.tsx',
        'packages/ui/src/components/disputes/DisputeDetail.tsx',
        'packages/ui/src/components/invitations/InvitationBatch.tsx',
        'packages/ui/src/components/mentors/MentorProfileCard.tsx',
        'packages/ui/src/components/mentors/MentorProfileEditor.tsx',
        'packages/ui/src/components/mentors/MentorOnboarding.tsx',
        'packages/ui/src/components/mentors/MentorReviews.tsx',
        'packages/ui/src/components/mentors/MentorSearch.tsx',
        'packages/ui/src/components/mentors/mentor-search.ts',
        'packages/ui/src/components/mentors/TechnologyChips.tsx',
        'packages/ui/src/components/mentors/technology-icons.ts',
        'packages/ui/src/components/notes/NoteReview.tsx',
        'packages/ui/src/components/operators/MetricSummary.tsx',
        'packages/ui/src/components/payments/PaymentStatus.tsx',
        'packages/ui/src/components/sessions/SessionCard.tsx',
        'packages/ui/src/components/sessions/WrittenAnswer.tsx',
        'packages/ui/src/components/ui/accordion.tsx',
        'packages/ui/src/components/ui/alert-dialog.tsx',
        'packages/ui/src/components/ui/alert.tsx',
        'packages/ui/src/components/ui/avatar.tsx',
        'packages/ui/src/components/ui/badge.tsx',
        'packages/ui/src/components/ui/breadcrumb.tsx',
        'packages/ui/src/components/ui/button.tsx',
        'packages/ui/src/components/ui/card.tsx',
        'packages/ui/src/components/ui/checkbox.tsx',
        'packages/ui/src/components/ui/dialog.tsx',
        'packages/ui/src/components/ui/dropdown-menu.tsx',
        'packages/ui/src/components/ui/input.tsx',
        'packages/ui/src/components/ui/label.tsx',
        'packages/ui/src/components/ui/pagination.tsx',
        'packages/ui/src/components/ui/popover.tsx',
        'packages/ui/src/components/ui/progress.tsx',
        'packages/ui/src/components/ui/radio-group.tsx',
        'packages/ui/src/components/ui/select.tsx',
        'packages/ui/src/components/ui/separator.tsx',
        'packages/ui/src/components/ui/skeleton.tsx',
        'packages/ui/src/components/ui/switch.tsx',
        'packages/ui/src/components/ui/tabs.tsx',
        'packages/ui/src/components/ui/textarea.tsx',
        'packages/ui/src/components/ui/tooltip.tsx',
        'scripts/setup/effects.mjs',
        'scripts/setup/index.mjs',
        'scripts/setup/run.mjs',
        'scripts/setup/steps.mjs',
      ],
      reportsDirectory: 'coverage/unit',
      reporter: ['text', 'json', 'html', 'lcov'],
      thresholds: {
        perFile: true,
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
