import { Migration } from '@mikro-orm/migrations';

/**
 * The password credential column on `users` (E01 Slice 4).
 *
 * Generated by `db:migration:create` from the entity, unchanged — unlike `auth-identity`
 * there is nothing to backfill, because a row that predates this column has no password
 * and null is exactly the right answer for it. The seeder plants a hash on the two
 * personas that need one; every other row stays null and keeps signing in through GitHub.
 *
 * `text`, not `varchar(60)`: 60 is bcrypt's output width and this project hashes with
 * `scrypt`. Pinning the width would pin the schema to an algorithm we do not use and close
 * the `argon2id` upgrade path; the encoding is the hashing service's business.
 *
 * Nullable is load-bearing, not lenient. A GitHub-only account genuinely has no password,
 * so `not null` would have no value to write for the rows `auth-identity` just verified,
 * and the column could not be added without inventing one.
 *
 * `down` drops the column, which reverses the schema exactly. It cannot preserve the
 * hashes — the column that held them is gone — which is the normal cost of an additive
 * column: `down` is a rollback path, not an undo. Rolling this back leaves every GitHub
 * account working, which is why Slice 4 reverts before Slice 2 when both must go.
 */
export class Migration20260910092433_auth_password extends Migration {

  override name = 'Migration20260910092433_auth_password';

  override up(): void | Promise<void> {
    this.addSql(`alter table "users" add "password_hash" text null;`);
  }

  override down(): void | Promise<void> {
    this.addSql(`alter table "users" drop column "password_hash";`);
  }

}
