import { Migration } from '@mikro-orm/migrations';

/**
 * The rate-limit counter table (E01 Slice 4, platform primitives B8).
 *
 * Generated by `db:migration:create` from `AuthRateLimit`, unchanged. It is worth reading
 * for what it does **not** contain: no `id`, no `created_at`, no `updated_at`. That is the
 * one documented exception to this schema's base-column rule, and the entity's docblock
 * carries the reasoning — a counter addressed by a natural text key is not a domain row.
 *
 * The `key` is a hashed bucket name (`<scope>:<kind>:<sha256hex>`), so this table holds no
 * email address and no IP address even though it is entirely built out of them. Anyone
 * restoring a backup of it learns how often a bucket was hit and nothing else.
 *
 * The index on `window_start` serves exactly one query: the prune that every `consume`
 * issues for rows older than the longest configured window. Every other access is a
 * primary-key upsert.
 *
 * `down` drops the table, which reverses the schema exactly and discards the live
 * counters. That is the right trade and not a data-loss concern: the rows are a
 * fifteen-minute-to-one-hour sliding record of failed attempts that the limiter deletes on
 * its own anyway. A rollback means every bucket restarts empty — the same state a fresh
 * deployment starts in.
 *
 * `cascade` on the drop is the generator's default and is a no-op here: nothing references
 * this table, because nothing may. It is deliberately unrelated to `users` — a counter
 * keyed on a *hash* cannot carry a foreign key, and a limit on an address that has no
 * account is exactly the case that matters most.
 */
export class Migration20260910095701_auth_rate_limits extends Migration {

  override name = 'Migration20260910095701_auth_rate_limits';

  override up(): void | Promise<void> {
    this.addSql(`create table "auth_rate_limits" ("key" text not null, "window_start" timestamptz not null, "count" int not null, primary key ("key"));`);
    this.addSql(`create index "auth_rate_limits_window_start_index" on "auth_rate_limits" ("window_start");`);
  }

  override down(): void | Promise<void> {
    this.addSql(`drop table if exists "auth_rate_limits" cascade;`);
  }

}
