import { useState, type ReactNode } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from '../src/components/ui/button';
import { Input } from '../src/components/ui/input';
import { Textarea } from '../src/components/ui/textarea';
import { Checkbox } from '../src/components/ui/checkbox';
import { Switch } from '../src/components/ui/switch';
import { RadioGroup, RadioGroupItem } from '../src/components/ui/radio-group';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '../src/components/ui/select';
import { Separator } from '../src/components/ui/separator';
import { Label } from '../src/components/ui/label';
import { Badge } from '../src/components/ui/badge';
import { Avatar, AvatarFallback } from '../src/components/ui/avatar';
import { Progress } from '../src/components/ui/progress';
import { Skeleton } from '../src/components/ui/skeleton';
import { Alert, AlertTitle, AlertDescription } from '../src/components/ui/alert';
import { Card } from '../src/components/ui/card';
import { EmptyState } from '../src/backend/feedback/EmptyState';
import { ErrorMessage } from '../src/backend/feedback/ErrorMessage';
import { FormField } from '../src/backend/forms/FormField';
import { LoadingMessage } from '../src/backend/feedback/LoadingMessage';
import { MentorIdentity } from '../src/components/mentors/MentorProfileCard';
import { MentorRatingSummary } from '../src/components/mentors/MentorReviews';
import { TechnologyChips } from '../src/components/mentors/TechnologyChips';
import { DurationSelector } from '../src/components/availability/AvailabilityPicker';
import { NotificationItem } from '../src/components/sessions/SessionCard';
import { AccessStatus } from '../src/components/auth/AccessStatus';
import { PaymentStatus } from '../src/components/payments/PaymentStatus';
import { WrittenAnswer } from '../src/components/sessions/WrittenAnswer';
import { Search, ArrowUpRight, CalendarDays, Check, Layers, MessageSquare, FileText } from 'lucide-react';

type Entry = { name:string; group:string; description:string; path:string; preview:ReactNode };
const primitive = (name:string,group:string,description:string,preview:ReactNode):Entry => ({name,group,description,preview,path:`/docs/primitives-${name.toLowerCase().replaceAll(' ','-')}--docs`});
const product = (name:string,slug:string,description:string,preview:ReactNode):Entry => ({name,group:'Product',description,preview,path:`/docs/product-${slug}--docs`});
const noAction = () => undefined;
const compactPanel = 'w-full [&_.dm-product-panel]:gap-2 [&_.dm-product-panel]:p-3 [&_.dm-product-title]:text-sm [&_.dm-product-heading]:text-base [&_.dm-product-heading]:leading-6 [&_.dm-product-muted]:text-xs [&_.dm-product-muted]:leading-4';
const entries:Entry[] = [
  primitive('Button','Actions','Three action types, each with four appearances.',<div className="dm-form-actions w-full"><Button intent="neutral" appearance="stroke">View profile</Button><Button>Book a session</Button></div>),
  primitive('Input','Forms','Text, password, date and numeric entry.',<Input placeholder="Your email address" aria-label="Email preview" />),
  primitive('Textarea','Forms','Room for an introduction, answer or note.',<Textarea placeholder="What would you like to work through?" aria-label="Textarea preview" />),
  primitive('Checkbox','Forms','Independent choices with checked and mixed states.',<div className="flex items-center gap-3 text-sm"><Checkbox checked aria-label="Selected option" /><span>Send me session reminders</span></div>),
  primitive('Radio group','Forms','One choice from a small set of options.',<RadioGroup defaultValue="25" aria-label="Session duration preview"><div className="flex items-center gap-2 text-sm"><RadioGroupItem value="25" aria-label="25 minutes" /><span>25 minutes</span></div><div className="flex items-center gap-2 text-sm"><RadioGroupItem value="50" aria-label="50 minutes" /><span>50 minutes</span></div></RadioGroup>),
  primitive('Switch','Forms','Change a setting with immediate feedback.',<div className="flex items-center gap-3 text-sm"><Switch checked aria-label="Notifications enabled" /><span>Email notifications</span></div>),
  primitive('Select','Forms','Choose a stack, timezone or other single value.',<Select defaultValue="typescript"><SelectTrigger aria-label="Stack preview"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="typescript">TypeScript</SelectItem><SelectItem value="react">React</SelectItem></SelectContent></Select>),
  primitive('Badge','Feedback','Compact labels for status and context.',<div className="flex flex-wrap gap-2"><Badge>Confirmed</Badge><Badge variant="secondary">Draft</Badge><Badge variant="outline">25 min</Badge></div>),
  primitive('Avatar','Identity','Image and initials with a reliable fallback.',<div className="flex gap-3"><Avatar><AvatarFallback>AM</AvatarFallback></Avatar><Avatar><AvatarFallback>ST</AvatarFallback></Avatar><Avatar><AvatarFallback>JC</AvatarFallback></Avatar></div>),
  primitive('Card','Layout','A container for related information.',<Card className="w-full p-4"><p className="text-sm font-medium">Your next conversation</p><p className="mt-2 text-xs text-muted-foreground">Work through one topic and decide what to do next.</p></Card>),
  primitive('Tabs','Navigation','Switch between related views in place.',<div className="dm-catalogue-tab-sample"><span>Upcoming</span><span>Past sessions</span></div>),
  primitive('Accordion','Navigation','Reveal details when they are needed.',<div className="w-full rounded-lg border border-border p-3 text-sm">How does a text session work? <span className="float-right">+</span></div>),
  primitive('Breadcrumb','Navigation','Show location within a deeper hierarchy.',<p className="text-sm text-muted-foreground">Workspace <span className="mx-2">/</span> Sessions <span className="mx-2">/</span> Details</p>),
  primitive('Pagination','Navigation','Browse records one page at a time.',<div className="flex gap-2"><Button intent="neutral" appearance="stroke" size="xs">Previous</Button><Button size="xs">1</Button><Button intent="neutral" appearance="ghost" size="xs">2</Button></div>),
  primitive('DropdownMenu','Overlays','Keep secondary actions near their context.',<div className="w-44 rounded-lg border border-border bg-card p-2 shadow-sm"><p className="rounded-md bg-muted px-2 py-1.5 text-sm">Edit profile</p><p className="px-2 py-1.5 text-sm">Copy link</p></div>),
  primitive('Dialog','Overlays','A focused task above the current view.',<div className="w-full rounded-xl border border-border bg-card p-4"><p className="text-sm font-medium">Edit availability</p><p className="mb-3 mt-1 text-xs text-muted-foreground">Keep your published times up to date.</p><div className="dm-form-actions"><Button size="xs">Save changes</Button></div></div>),
  primitive('AlertDialog','Overlays','State the consequence before confirmation.',<div className="text-center"><p className="mb-3 text-sm">Cancel this session?</p><Button intent="neutral" appearance="stroke" size="xs">Keep session</Button></div>),
  primitive('Popover','Overlays','Contextual details without leaving the page.',<div className="rounded-xl border border-border bg-card p-4 text-sm shadow-sm"><CalendarDays size={20} className="mb-2" />Europe/Warsaw<span className="mt-1 block text-xs text-muted-foreground">Times follow your selected timezone.</span></div>),
  primitive('Tooltip','Overlays','Short help for a familiar control.',<div className="rounded-md bg-foreground px-3 py-2 text-xs text-background">Copy public profile link</div>),
  primitive('Alert','Feedback','Explain an outcome and the next available action.',<Alert><AlertTitle>Changes saved</AlertTitle><AlertDescription>Your profile is up to date.</AlertDescription></Alert>),
  primitive('Progress','Feedback','Show how much of a task is complete.',<div className="w-full"><p className="mb-3 text-xs text-muted-foreground">Profile completeness: 75%</p><Progress value={75} aria-label="Profile completeness" /></div>),
  primitive('Skeleton','Feedback','Reserve space while content is loading.',<div className="flex w-full items-center gap-3"><Skeleton className="size-10 rounded-full" /><div className="flex-1 space-y-2"><Skeleton className="h-3 w-4/5" /><Skeleton className="h-3 w-3/5" /></div></div>),
  primitive('Separator','Layout','A dividing line between groups.',<div className="w-full"><p className="mb-4 text-xs text-muted-foreground">Session details</p><Separator /><p className="mt-4 text-xs text-muted-foreground">Your written answer</p></div>),
  primitive('Label','Forms','A visible name for an associated control.',<div className="w-full space-y-1"><Label>Public profile name</Label><Input value="Alex Morgan" readOnly aria-label="Profile name preview" /></div>),
  {name:'FormField',group:'Forms',description:'Label, required marker, description and linked error.',path:'/docs/backend-forms-formfield--docs',preview:<FormField id="gallery-field" label="Session topic" description="Choose one focused question.">{control=><Input {...control} value="React state" readOnly />}</FormField>},
  {name:'Error message',group:'Feedback',description:'Explain a failure and how to try again.',path:'/docs/backend-feedback-errormessage--docs',preview:<ErrorMessage message="Sessions could not be loaded." action={<Button intent="neutral" appearance="stroke" size="xs">Try again</Button>} />},
  {name:'CrudForm',group:'Patterns',description:'Validation, saving and recovery, with Cancel before the right-aligned submit action.',path:'/docs/backend-forms-crudform--docs',preview:<div className="w-full space-y-3"><Input placeholder="Your headline" aria-label="Form preview" /><div className="dm-form-actions"><Button size="sm" intent="neutral" appearance="ghost">Cancel</Button><Button size="sm">Save profile</Button></div></div>},
  {name:'DataTable',group:'Patterns',description:'Named columns, row actions and keyboard-accessible horizontal scrolling.',path:'/docs/backend-tables-datatable--docs',preview:<div className="w-full space-y-3">{['Mentor: Topic: Status','Sam: React state: Confirmed','Jordan: TypeScript: Upcoming'].map(x=><p key={x} className="border-b border-border pb-2 text-xs">{x}</p>)}</div>},
  {name:'Empty state',group:'Feedback',description:'Explain what is absent and how to get started.',path:'/docs/backend-feedback-emptystate--docs',preview:<EmptyState title="No sessions yet" description="Choose a time to begin." className="w-full !p-4" />},
  {name:'Loading',group:'Feedback',description:'Announce loading progress to assistive technology.',path:'/docs/backend-feedback-loadingmessage--docs',preview:<LoadingMessage message="Loading your sessions…" />},
  {name:'Workspace',group:'Patterns',description:'Responsive navigation, identity and page content.',path:'/docs/backend-layout-appshell--docs',preview:<div className="flex h-28 w-full rounded-lg border border-border"><div className="w-1/3 border-r border-border p-3"><Layers size={18} /><div className="mt-3 h-2 rounded bg-primary/20" /></div><div className="flex-1 p-3"><div className="h-2 w-3/4 rounded bg-muted" /><div className="mt-3 h-12 rounded border border-border" /></div></div>},
  {name:'Authentication',group:'Patterns',description:'Full-width neutral GitHub and primary email actions, separate back navigation and verification states.',path:'/docs/backend-layout-authlayout--docs',preview:<div className="w-full space-y-2 text-center"><Button size="sm" className="w-full" intent="neutral" appearance="stroke">Continue with GitHub</Button><Button size="sm" className="w-full">Continue with email</Button><Button size="xs" intent="neutral" appearance="ghost">Back</Button></div>},
  product('Mentor profiles','mentors','Identity, public work, technology icons and optional reviews.',<div className="w-full space-y-4"><MentorIdentity name="Alex Laurent" headline="Staff engineer: developer tooling" initials="AL" /><TechnologyChips stacks={['TypeScript','React']} /></div>),
  product('Mentor search','mentor-search','Search names and topics, combine technology, price and availability filters, and open the matching profile.',<div className="w-full space-y-4"><div className="flex items-center gap-3 rounded-xl border border-border p-3"><Search size={20} className="text-primary" /><span className="text-sm">React testing</span></div><TechnologyChips stacks={['React','TypeScript']} /><p className="text-xs text-muted-foreground">Price and availability filters</p></div>),
  product('Mentor ratings and reviews','mentors','Average ratings, written feedback and an accessible review form after a session. Demo reviews are fictional; the application checks eligibility and saves them.',<div className="w-full space-y-3"><MentorRatingSummary average={14/3} reviewCount={3}/><p className="text-sm">The explanation helped me work out what to do next.</p><p className="text-xs text-muted-foreground">Fictional demo feedback</p></div>),
  product('Account access','account-access','Verification, expired sessions and every invitation recovery state.',<div className={compactPanel}><AccessStatus state="verified" /></div>),
  product('Availability','availability','Times with timezones, reasons a slot is unavailable, and prices for 25/50-minute sessions.',<div className="w-full"><DurationSelector options={[{minutes:25,price:'EUR 45'},{minutes:50,price:'EUR 80'}]} selected={25} onChange={noAction} /></div>),
  product('Booking summary','booking','Selected time, duration and total, plus cancellation consequences.',<Card className="w-full space-y-3 p-4"><div className="flex items-center justify-between gap-3 text-sm"><span>25-minute text session</span><Badge variant="outline">9 Sep</Badge></div><Separator /><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">Europe/Warsaw: 14:00</span><strong className="text-sm">EUR 45</strong></div></Card>),
  product('Payments and payouts','payments','Payment confirmation and recovery, with Connect and transfer states.',<div className={compactPanel}><PaymentStatus state="confirmed" /></div>),
  product('Sessions and notifications','sessions','Upcoming and past sessions, session headers and read/unread notifications.',<div className="w-full [&_.dm-notification]:p-3 [&_.dm-product-title]:text-sm"><NotificationItem title="Your session is confirmed" description="Alex Laurent: 9 Sep, 14:00 Europe/Warsaw" createdAt="2026-09-07T10:00:00Z" timeLabel="Just now" read onMarkRead={noAction} href="#session-preview" /></div>),
  product('Written answers','written-answer-and-transcript','Own and received messages, delivery states and a composer slot. Written answers appear after the session ends.',<div className={compactPanel}><WrittenAnswer state="posted" mentorName="Alex Laurent" body={<p>Validate at the boundary. Keep ownership checks in the service.</p>} /></div>),
  product('Private notes','private-notes','Draft, approve or request changes, with a required comment and version history.',<Card className="w-full space-y-3 p-4"><div className="flex items-center justify-between gap-2 text-xs"><span>Private note: v2</span><Badge variant="outline">For approval</Badge></div><p className="text-sm font-medium">A clearer API boundary</p><div className="dm-form-actions"><Button size="xs" intent="neutral" appearance="stroke">Request changes</Button><Button size="xs">Approve note</Button></div></Card>),
  product('Invitation batches','invitation-batches','Later operator tools for invitation capacity and first-session deadlines.',<div className="w-full space-y-3"><div className="flex justify-between text-sm"><strong>September batch</strong><span>4 / 20</span></div><Progress value={20} aria-label="Invitations sent preview" /><div className="flex flex-wrap gap-2"><Badge variant="secondary">Accepted</Badge><Badge variant="outline">Published</Badge></div></div>),
  product('Operator metrics','operator-metrics','Paid sessions, booking-to-start time and note declines, including unavailable data.',<div className="grid w-full grid-cols-2 gap-3"><Card className="p-3"><p className="text-xs text-muted-foreground">Paid sessions</p><p className="mt-2 text-2xl font-semibold">12</p></Card><Card className="p-3"><p className="text-xs text-muted-foreground">Note declines</p><p className="mt-2 text-2xl font-semibold">2</p></Card></div>),
  product('Disputes','disputes','Authorized evidence and recorded outcomes, separate from any refund action.',<Card className="w-full space-y-3 p-4"><div className="flex justify-between text-sm"><strong>Dispute D-101</strong><Badge variant="outline">Open</Badge></div><p className="text-xs text-muted-foreground">Review the agreed question and the written answer.</p><div className="dm-form-actions"><Button size="xs" intent="neutral" appearance="stroke">Record outcome</Button></div></Card>),
  product('Mentor workspace','mentor-workspace','Profile, availability, prices and private-note editing through the shared form.',<div className="w-full space-y-2"><Label>25-minute price</Label><Input type="number" value={45} readOnly aria-label="Price preview" /><div className="dm-form-actions"><Button size="sm">Save prices</Button></div></div>),
  product('Operator settings','operator-settings','Schema-validated price bounds and platform fee configuration.',<div className="grid w-full grid-cols-2 gap-3"><div className="space-y-1"><Label>Minimum</Label><Input type="number" value={5} readOnly aria-label="Minimum price preview" /></div><div className="space-y-1"><Label>Maximum</Label><Input type="number" value={300} readOnly aria-label="Maximum price preview" /></div><p className="col-span-2 text-xs text-muted-foreground">Example bounds: EUR</p></div>),
  product('First booking flow','reference-flow','Choose a mentor, time and duration, then see the price update in the summary.',<div className="w-full space-y-3"><MentorIdentity name="Alex Laurent" headline="Text mentoring: TypeScript" initials="AL" /><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">14:00</Badge><span className="text-xs text-muted-foreground">→</span><Badge variant="outline">25 min</Badge><span className="text-xs text-muted-foreground">→</span><Badge>EUR 45</Badge></div></div>),
];

function ComponentGallery() {
  const [query,setQuery]=useState('');
  const [group,setGroup]=useState('All');
  const visible=entries.filter(entry=>(group==='All'||entry.group===group)&&`${entry.name} ${entry.description}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="dm-catalogue"><div className="dm-catalogue-heading"><div><p className="ds-eyebrow">DEVMENTOR LIBRARY</p><h2>Component gallery</h2><p>Find a component and open its props, states and usage examples.</p></div><span className="dm-catalogue-count">{entries.length} families</span></div>
    <div className="dm-catalogue-tools"><div className="dm-catalogue-search"><Search size={18} aria-hidden="true" /><Input aria-label="Search components" placeholder="Find a component…" value={query} onChange={event=>setQuery(event.target.value)} /></div><div className="dm-catalogue-filters" role="group" aria-label="Component categories">{['All','Actions','Forms','Identity','Layout','Navigation','Overlays','Feedback','Patterns','Product'].map(category=><Button key={category} size="xs" intent={group===category?'primary':'neutral'} appearance={group===category?'lighter':'ghost'} aria-pressed={group===category} onClick={()=>setGroup(category)}>{category}</Button>)}</div></div>
    <p className="sr-only" role="status">{visible.length} component families</p>
    <div className="dm-catalogue-grid">{visible.map(entry=><article className="dm-catalogue-card" key={entry.name}><div className="dm-catalogue-preview" aria-hidden="true" inert>{entry.preview}</div><div className="dm-catalogue-card-body"><span>{entry.group}</span><h3><a href={`?path=${entry.path}`} target="_top">{entry.name}<ArrowUpRight size={16} aria-hidden="true" /></a></h3><p>{entry.description}</p></div></article>)}</div>
    {visible.length===0&&<EmptyState title="No matching components" description="Try another name or select a different category." action={<Button intent="neutral" appearance="stroke" onClick={()=>{setQuery('');setGroup('All');}}>Clear filters</Button>} />}
    <div className="dm-catalogue-footer"><Check size={18} aria-hidden="true" /><p>Use shared components, document their states and label the action a person can take.</p><MessageSquare size={18} aria-hidden="true" /><FileText size={18} aria-hidden="true" /></div>
  </section>;
}
const meta={title:'Design system/Components',tags:['autodocs'],parameters:{docs:{description:{component:'Browse DevMentor components. Open a family for interactive states, props and usage examples.'}}}} satisfies Meta;
export default meta;
type Story=StoryObj<typeof meta>;
export const Gallery:Story={render:()=> <ComponentGallery />};
