import type { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from '../src/components/ui/button';
import { CalendarDays, Clock3, UserRound, ArrowRight, ArrowLeft, Check, X, Plus, Search, SlidersHorizontal, Bell, Settings, LogOut, FileText, ExternalLink, Mail, ShieldCheck, CircleAlert, Copy, LoaderCircle } from 'lucide-react';

const meta = {
  title: 'Foundations/Tokens', tags: ['autodocs'],
  parameters: { docs: { description: { component: 'These examples use the same DevMentor CSS variables as the application. Blue and Green each support light and dark themes.' } } },
} satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
const roles = ['background', 'foreground', 'card', 'primary', 'primary-foreground', 'secondary', 'muted', 'muted-foreground', 'accent', 'destructive', 'border', 'input', 'ring'];
const types = [['Display',56,64,550],['Heading XL',40,48,550],['Heading L',32,40,550],['Heading M',24,32,550],['Heading S',20,28,550],['Body L',18,24,400],['Body M',16,24,400],['Body S',14,20,400],['Label S',14,20,500],['Caption',12,16,400]] as const;
export const ActiveTheme: Story = { render: () => <section className="space-y-8"><div><h2 className="text-2xl font-medium">Semantic colors</h2><p className="mt-2 text-sm text-muted-foreground">Choose the token for the surface, text or action you need. Use Theme to check its colors in another appearance.</p></div><div className="ds-token-grid">{roles.map(role => <div className="ds-token" key={role}><div className="ds-token-swatch" style={{background:`var(--${role})`}} /><div className="ds-token-label"><code>--{role}</code></div></div>)}</div><div className="ds-token-grid">{['information','success','warning','error','faded'].map(tone => <div className="ds-token" key={tone}><div className="p-5" style={{background:`var(--dm-state-${tone}-lighter)`,color:`var(--dm-state-${tone}-dark)`}}>{tone}</div><div className="ds-token-label">Status: text + surface</div></div>)}</div><p className="text-sm text-muted-foreground">Name each status in text, including success and error states. Brand color alone cannot explain a status.</p></section> };
export const Typography: Story = { render: () => <section className="space-y-8">
  <div><h2 className="text-2xl font-medium">Inter for the interface</h2><p className="mt-2 text-sm text-muted-foreground">Use locally bundled Inter Variable for interface text, controls and headings. Use DM Mono for the DevMentor wordmark, code and identifiers. Keep body copy within 65 characters per line and use semantic heading levels.</p></div>
  <div className="space-y-4 rounded-xl border border-border p-6"><h3 className="text-lg font-medium">DM Mono for the wordmark</h3><p style={{fontFamily:'var(--dm-font-mono)',fontSize:'clamp(25px, 5vw, 36px)',lineHeight:1.3,fontWeight:500,letterSpacing:'-.06em'}}>DevMentor<span aria-hidden="true" style={{fontFamily:'var(--dm-font-family)',color:'var(--dm-action-primary-label)',marginLeft:8}}>✦</span></p><p className="max-w-xl text-sm text-muted-foreground">The logo uses the bundled monospace font for a programming style. It is legible in both themes; the surrounding interface uses Inter.</p></div>
  {types.map(([name,size,line,weight]) => <div key={name} className="border-b border-border pb-5"><p className="mb-3 font-mono text-xs text-muted-foreground">{name}: {size}/{line}: {weight}</p><p style={{fontFamily:'var(--dm-font-family)',fontSize:size > 32 ? `clamp(28px, 5vw, ${size}px)` : `${size}px`,lineHeight:`${line/size}`,fontWeight:weight,letterSpacing:weight===550?'-.01em':'normal'}}>Choose a time for your session.</p></div>)}
  <div className="dm-code rounded-lg bg-muted p-5 text-sm">const progress = await learnTogether();</div>
  <p className="dm-numeric">Prices and time use tabular figures: EUR 45.00: 14:30: 25 / 50 min</p>
</section> };
export const SpacingAndRadius: Story = { render: () => <section className="space-y-8"><h2 className="text-2xl font-medium">Spacing and radius</h2><p className="text-sm text-muted-foreground">Use 8px for related text, 16px between paragraphs, 24px inside panels, 32px between components and 48 to 64px between page sections. Use semantic gap tokens to keep these spaces consistent.</p><div className="space-y-3">{[2,4,6,8,10,12,14,16,24,32,40,48].map(size => <div key={size} className="flex items-center gap-5"><code className="w-36 text-xs">--dm-space-{size}</code><div className="h-3 rounded-sm bg-primary" style={{width:`var(--dm-space-${size})`}} /><span className="text-xs text-muted-foreground">{size}px</span></div>)}</div><div className="flex flex-wrap gap-5">{[4,8,10,12,16,24].map(size => <div key={size} className="border border-border p-6 text-xs" style={{borderRadius:`var(--dm-radius-${size})`}}>{size}px radius</div>)}</div><div className="flex flex-wrap gap-8">{['xs','popover','modal'].map(shadow => <div key={shadow} className="rounded-xl border border-border bg-card p-8 text-sm" style={{boxShadow:`var(--dm-shadow-${shadow})`}}>{shadow}</div>)}</div></section> };
export const Motion: Story = { render: () => <section className="max-w-xl space-y-6"><h2 className="text-2xl font-medium">Motion and feedback</h2><dl className="grid grid-cols-2 gap-4 text-sm"><dt>Control feedback</dt><dd>120 ms</dd><dt>Menus and popovers</dt><dd>180 ms</dd><dt>Dialogs and larger surfaces</dt><dd>240 ms</dd></dl><Button>Hover or focus this action</Button><p className="text-sm text-muted-foreground">Use opacity and short translations. Keep focus visible throughout a transition. Reduced-motion preferences remove nonessential movement; pending actions still have text and an accessible status.</p><p className="text-sm text-muted-foreground">Do not animate an action into success until the server confirms it.</p></section> };
const icons = {CalendarDays,Clock3,UserRound,ArrowRight,ArrowLeft,Check,X,Plus,Search,SlidersHorizontal,Bell,Settings,LogOut,FileText,ExternalLink,Mail,ShieldCheck,CircleAlert,Copy,LoaderCircle};
export const Iconography: Story = { render: () => <section className="space-y-6"><h2 className="text-2xl font-medium">Interface icons</h2><p className="max-w-2xl text-sm text-muted-foreground">Use 20px interface icons with currentColor. Decorative icons are hidden from assistive technology; icon-only actions need an accessible name. Prefer familiar symbols and pair unfamiliar ones with text.</p><div className="ds-token-grid">{Object.entries(icons).map(([name,Icon])=><div className="flex flex-col items-center gap-4 rounded-xl border border-border p-5" key={name}><Icon size={20} aria-hidden="true" /><code className="text-xs">{name}</code></div>)}</div></section> };
export const ResponsiveLayout: Story = { render: () => <section className="space-y-6"><h2 className="text-2xl font-medium">Responsive layout</h2><div className="dm-product-grid">{['Mentor identity','Available time','Session summary'].map(title=><div className="rounded-xl border border-border p-6" key={title}><h3 className="font-medium">{title}</h3><p className="mt-3 text-sm text-muted-foreground">Cards stack as their container narrows. Reading order and keyboard order stay the same.</p></div>)}</div><ul className="list-disc space-y-2 pl-5 text-sm text-muted-foreground"><li>24px page gutters on compact screens, 48px on wide layouts.</li><li>1200px maximum content width; readable prose stays within 65ch.</li><li>Stack booking details before its primary action on mobile.</li><li>Wide data tables scroll inside a named, keyboard-focusable region.</li><li>Review at 320, 390, 768 and 1440 CSS px, with long text and 200% zoom.</li></ul></section> };
